# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruwabe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guarantors',
            new_name='Guarantor',
        ),
    ]
