# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruwabe_app', '0002_auto_20180408_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
