# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruwabe_app', '0004_auto_20180408_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='source',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
