# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruwabe_app', '0005_auto_20180408_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='source',
            field=models.URLField(null=True),
        ),
    ]
